/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as MasterDashboardRouteImport } from './routes/master-dashboard'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as RegisterSalonRouteImport } from './routes/register-salon'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WeddingPackagesRouteImport } from './routes/wedding-packages'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as HairstylesIndexRouteImport } from './routes/hairstyles/index'
import { Route as HairstylesSlugRouteImport } from './routes/hairstyles/$slug'
import { Route as MasterDashboardIndexRouteImport } from './routes/master-dashboard.index'
import { Route as MasterDashboardAdminsRouteImport } from './routes/master-dashboard.admins'
import { Route as MasterDashboardApprovalsRouteImport } from './routes/master-dashboard.approvals'
import { Route as MasterDashboardBookingsRouteImport } from './routes/master-dashboard.bookings'
import { Route as MasterDashboardCustomersRouteImport } from './routes/master-dashboard.customers'
import { Route as MasterDashboardHairstylesRouteImport } from './routes/master-dashboard.hairstyles'
import { Route as MasterDashboardLocationsRouteImport } from './routes/master-dashboard.locations'
import { Route as MasterDashboardMessagesRouteImport } from './routes/master-dashboard.messages'
import { Route as MasterDashboardNotificationsRouteImport } from './routes/master-dashboard.notifications'
import { Route as MasterDashboardOffersRouteImport } from './routes/master-dashboard.offers'
import { Route as MasterDashboardPaymentGatewayRouteImport } from './routes/master-dashboard.payment-gateway'
import { Route as MasterDashboardReportsRouteImport } from './routes/master-dashboard.reports'
import { Route as MasterDashboardServicesRouteImport } from './routes/master-dashboard.services'
import { Route as MasterDashboardSettingsRouteImport } from './routes/master-dashboard.settings'
import { Route as MasterDashboardSubscriptionsRouteImport } from './routes/master-dashboard.subscriptions'
import { Route as MasterDashboardSupportRouteImport } from './routes/master-dashboard.support'
import { Route as SalonsIndexRouteImport } from './routes/salons/index'
import { Route as SalonsSlugRouteImport } from './routes/salons/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDashboardRoute = MasterDashboardRouteImport.update({
  id: '/master-dashboard',
  path: '/master-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSalonRoute = RegisterSalonRouteImport.update({
  id: '/register-salon',
  path: '/register-salon',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingPackagesRoute = WeddingPackagesRouteImport.update({
  id: '/wedding-packages',
  path: '/wedding-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const HairstylesIndexRoute = HairstylesIndexRouteImport.update({
  id: '/hairstyles/',
  path: '/hairstyles/',
  getParentRoute: () => rootRouteImport,
} as any)
const HairstylesSlugRoute = HairstylesSlugRouteImport.update({
  id: '/hairstyles/$slug',
  path: '/hairstyles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDashboardIndexRoute = MasterDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasterDashboardRoute,
} as any)
const MasterDashboardAdminsRoute = MasterDashboardAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => MasterDashboardRoute,
} as any)
const MasterDashboardApprovalsRoute =
  MasterDashboardApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => MasterDashboardRoute,
  } as any)
const MasterDashboardBookingsRoute = MasterDashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => MasterDashboardRoute,
} as any)
const MasterDashboardCustomersRoute =
  MasterDashboardCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => MasterDashboardRoute,
  } as any)
const MasterDashboardHairstylesRoute =
  MasterDashboardHairstylesRouteImport.update({
    id: '/hairstyles',
    path: '/hairstyles',
    getParentRoute: () => MasterDashboardRoute,
  } as any)
const MasterDashboardLocationsRoute =
  MasterDashboardLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => MasterDashboardRoute,
  } as any)
const MasterDashboardMessagesRoute = MasterDashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MasterDashboardRoute,
} as any)
const MasterDashboardNotificationsRoute =
  MasterDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => MasterDashboardRoute,
  } as any)
const MasterDashboardOffersRoute = MasterDashboardOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => MasterDashboardRoute,
} as any)
const MasterDashboardPaymentGatewayRoute =
  MasterDashboardPaymentGatewayRouteImport.update({
    id: '/payment-gateway',
    path: '/payment-gateway',
    getParentRoute: () => MasterDashboardRoute,
  } as any)
const MasterDashboardReportsRoute = MasterDashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MasterDashboardRoute,
} as any)
const MasterDashboardServicesRoute = MasterDashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => MasterDashboardRoute,
} as any)
const MasterDashboardSettingsRoute = MasterDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MasterDashboardRoute,
} as any)
const MasterDashboardSubscriptionsRoute =
  MasterDashboardSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => MasterDashboardRoute,
  } as any)
const MasterDashboardSupportRoute = MasterDashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MasterDashboardRoute,
} as any)
const SalonsIndexRoute = SalonsIndexRouteImport.update({
  id: '/salons/',
  path: '/salons/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsSlugRoute = SalonsSlugRouteImport.update({
  id: '/salons/$slug',
  path: '/salons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/book-demo': typeof BookDemoRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/master-dashboard': typeof MasterDashboardRouteWithChildren
  '/offers': typeof OffersRoute
  '/register-salon': typeof RegisterSalonRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/wedding-packages': typeof WeddingPackagesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/hairstyles/$slug': typeof HairstylesSlugRoute
  '/master-dashboard/admins': typeof MasterDashboardAdminsRoute
  '/master-dashboard/approvals': typeof MasterDashboardApprovalsRoute
  '/master-dashboard/bookings': typeof MasterDashboardBookingsRoute
  '/master-dashboard/customers': typeof MasterDashboardCustomersRoute
  '/master-dashboard/hairstyles': typeof MasterDashboardHairstylesRoute
  '/master-dashboard/locations': typeof MasterDashboardLocationsRoute
  '/master-dashboard/messages': typeof MasterDashboardMessagesRoute
  '/master-dashboard/notifications': typeof MasterDashboardNotificationsRoute
  '/master-dashboard/offers': typeof MasterDashboardOffersRoute
  '/master-dashboard/payment-gateway': typeof MasterDashboardPaymentGatewayRoute
  '/master-dashboard/reports': typeof MasterDashboardReportsRoute
  '/master-dashboard/services': typeof MasterDashboardServicesRoute
  '/master-dashboard/settings': typeof MasterDashboardSettingsRoute
  '/master-dashboard/subscriptions': typeof MasterDashboardSubscriptionsRoute
  '/master-dashboard/support': typeof MasterDashboardSupportRoute
  '/salons/$slug': typeof SalonsSlugRoute
  '/hairstyles/': typeof HairstylesIndexRoute
  '/master-dashboard/': typeof MasterDashboardIndexRoute
  '/salons/': typeof SalonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/book-demo': typeof BookDemoRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/offers': typeof OffersRoute
  '/register-salon': typeof RegisterSalonRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/wedding-packages': typeof WeddingPackagesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/hairstyles/$slug': typeof HairstylesSlugRoute
  '/master-dashboard/admins': typeof MasterDashboardAdminsRoute
  '/master-dashboard/approvals': typeof MasterDashboardApprovalsRoute
  '/master-dashboard/bookings': typeof MasterDashboardBookingsRoute
  '/master-dashboard/customers': typeof MasterDashboardCustomersRoute
  '/master-dashboard/hairstyles': typeof MasterDashboardHairstylesRoute
  '/master-dashboard/locations': typeof MasterDashboardLocationsRoute
  '/master-dashboard/messages': typeof MasterDashboardMessagesRoute
  '/master-dashboard/notifications': typeof MasterDashboardNotificationsRoute
  '/master-dashboard/offers': typeof MasterDashboardOffersRoute
  '/master-dashboard/payment-gateway': typeof MasterDashboardPaymentGatewayRoute
  '/master-dashboard/reports': typeof MasterDashboardReportsRoute
  '/master-dashboard/services': typeof MasterDashboardServicesRoute
  '/master-dashboard/settings': typeof MasterDashboardSettingsRoute
  '/master-dashboard/subscriptions': typeof MasterDashboardSubscriptionsRoute
  '/master-dashboard/support': typeof MasterDashboardSupportRoute
  '/salons/$slug': typeof SalonsSlugRoute
  '/hairstyles': typeof HairstylesIndexRoute
  '/master-dashboard': typeof MasterDashboardIndexRoute
  '/salons': typeof SalonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/book-demo': typeof BookDemoRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/master-dashboard': typeof MasterDashboardRouteWithChildren
  '/offers': typeof OffersRoute
  '/register-salon': typeof RegisterSalonRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/wedding-packages': typeof WeddingPackagesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/hairstyles/$slug': typeof HairstylesSlugRoute
  '/master-dashboard/admins': typeof MasterDashboardAdminsRoute
  '/master-dashboard/approvals': typeof MasterDashboardApprovalsRoute
  '/master-dashboard/bookings': typeof MasterDashboardBookingsRoute
  '/master-dashboard/customers': typeof MasterDashboardCustomersRoute
  '/master-dashboard/hairstyles': typeof MasterDashboardHairstylesRoute
  '/master-dashboard/locations': typeof MasterDashboardLocationsRoute
  '/master-dashboard/messages': typeof MasterDashboardMessagesRoute
  '/master-dashboard/notifications': typeof MasterDashboardNotificationsRoute
  '/master-dashboard/offers': typeof MasterDashboardOffersRoute
  '/master-dashboard/payment-gateway': typeof MasterDashboardPaymentGatewayRoute
  '/master-dashboard/reports': typeof MasterDashboardReportsRoute
  '/master-dashboard/services': typeof MasterDashboardServicesRoute
  '/master-dashboard/settings': typeof MasterDashboardSettingsRoute
  '/master-dashboard/subscriptions': typeof MasterDashboardSubscriptionsRoute
  '/master-dashboard/support': typeof MasterDashboardSupportRoute
  '/salons/$slug': typeof SalonsSlugRoute
  '/hairstyles/': typeof HairstylesIndexRoute
  '/master-dashboard/': typeof MasterDashboardIndexRoute
  '/salons/': typeof SalonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/book-demo'
    | '/contact'
    | '/forgot-password'
    | '/master-dashboard'
    | '/offers'
    | '/register-salon'
    | '/reset-password'
    | '/services'
    | '/wedding-packages'
    | '/admin'
    | '/owner'
    | '/hairstyles/$slug'
    | '/master-dashboard/admins'
    | '/master-dashboard/approvals'
    | '/master-dashboard/bookings'
    | '/master-dashboard/customers'
    | '/master-dashboard/hairstyles'
    | '/master-dashboard/locations'
    | '/master-dashboard/messages'
    | '/master-dashboard/notifications'
    | '/master-dashboard/offers'
    | '/master-dashboard/payment-gateway'
    | '/master-dashboard/reports'
    | '/master-dashboard/services'
    | '/master-dashboard/settings'
    | '/master-dashboard/subscriptions'
    | '/master-dashboard/support'
    | '/salons/$slug'
    | '/hairstyles/'
    | '/master-dashboard/'
    | '/salons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/book-demo'
    | '/contact'
    | '/forgot-password'
    | '/offers'
    | '/register-salon'
    | '/reset-password'
    | '/services'
    | '/wedding-packages'
    | '/admin'
    | '/owner'
    | '/hairstyles/$slug'
    | '/master-dashboard/admins'
    | '/master-dashboard/approvals'
    | '/master-dashboard/bookings'
    | '/master-dashboard/customers'
    | '/master-dashboard/hairstyles'
    | '/master-dashboard/locations'
    | '/master-dashboard/messages'
    | '/master-dashboard/notifications'
    | '/master-dashboard/offers'
    | '/master-dashboard/payment-gateway'
    | '/master-dashboard/reports'
    | '/master-dashboard/services'
    | '/master-dashboard/settings'
    | '/master-dashboard/subscriptions'
    | '/master-dashboard/support'
    | '/salons/$slug'
    | '/hairstyles'
    | '/master-dashboard'
    | '/salons'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/account'
    | '/auth'
    | '/book-demo'
    | '/contact'
    | '/forgot-password'
    | '/master-dashboard'
    | '/offers'
    | '/register-salon'
    | '/reset-password'
    | '/services'
    | '/wedding-packages'
    | '/_authenticated/admin'
    | '/_authenticated/owner'
    | '/hairstyles/$slug'
    | '/master-dashboard/admins'
    | '/master-dashboard/approvals'
    | '/master-dashboard/bookings'
    | '/master-dashboard/customers'
    | '/master-dashboard/hairstyles'
    | '/master-dashboard/locations'
    | '/master-dashboard/messages'
    | '/master-dashboard/notifications'
    | '/master-dashboard/offers'
    | '/master-dashboard/payment-gateway'
    | '/master-dashboard/reports'
    | '/master-dashboard/services'
    | '/master-dashboard/settings'
    | '/master-dashboard/subscriptions'
    | '/master-dashboard/support'
    | '/salons/$slug'
    | '/hairstyles/'
    | '/master-dashboard/'
    | '/salons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BookDemoRoute: typeof BookDemoRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MasterDashboardRoute: typeof MasterDashboardRouteWithChildren
  OffersRoute: typeof OffersRoute
  RegisterSalonRoute: typeof RegisterSalonRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  WeddingPackagesRoute: typeof WeddingPackagesRoute
  HairstylesSlugRoute: typeof HairstylesSlugRoute
  SalonsSlugRoute: typeof SalonsSlugRoute
  HairstylesIndexRoute: typeof HairstylesIndexRoute
  SalonsIndexRoute: typeof SalonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-dashboard': {
      id: '/master-dashboard'
      path: '/master-dashboard'
      fullPath: '/master-dashboard'
      preLoaderRoute: typeof MasterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-salon': {
      id: '/register-salon'
      path: '/register-salon'
      fullPath: '/register-salon'
      preLoaderRoute: typeof RegisterSalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-packages': {
      id: '/wedding-packages'
      path: '/wedding-packages'
      fullPath: '/wedding-packages'
      preLoaderRoute: typeof WeddingPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/hairstyles/': {
      id: '/hairstyles/'
      path: '/hairstyles'
      fullPath: '/hairstyles/'
      preLoaderRoute: typeof HairstylesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hairstyles/$slug': {
      id: '/hairstyles/$slug'
      path: '/hairstyles/$slug'
      fullPath: '/hairstyles/$slug'
      preLoaderRoute: typeof HairstylesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-dashboard/': {
      id: '/master-dashboard/'
      path: '/'
      fullPath: '/master-dashboard/'
      preLoaderRoute: typeof MasterDashboardIndexRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/admins': {
      id: '/master-dashboard/admins'
      path: '/admins'
      fullPath: '/master-dashboard/admins'
      preLoaderRoute: typeof MasterDashboardAdminsRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/approvals': {
      id: '/master-dashboard/approvals'
      path: '/approvals'
      fullPath: '/master-dashboard/approvals'
      preLoaderRoute: typeof MasterDashboardApprovalsRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/bookings': {
      id: '/master-dashboard/bookings'
      path: '/bookings'
      fullPath: '/master-dashboard/bookings'
      preLoaderRoute: typeof MasterDashboardBookingsRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/customers': {
      id: '/master-dashboard/customers'
      path: '/customers'
      fullPath: '/master-dashboard/customers'
      preLoaderRoute: typeof MasterDashboardCustomersRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/hairstyles': {
      id: '/master-dashboard/hairstyles'
      path: '/hairstyles'
      fullPath: '/master-dashboard/hairstyles'
      preLoaderRoute: typeof MasterDashboardHairstylesRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/locations': {
      id: '/master-dashboard/locations'
      path: '/locations'
      fullPath: '/master-dashboard/locations'
      preLoaderRoute: typeof MasterDashboardLocationsRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/messages': {
      id: '/master-dashboard/messages'
      path: '/messages'
      fullPath: '/master-dashboard/messages'
      preLoaderRoute: typeof MasterDashboardMessagesRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/notifications': {
      id: '/master-dashboard/notifications'
      path: '/notifications'
      fullPath: '/master-dashboard/notifications'
      preLoaderRoute: typeof MasterDashboardNotificationsRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/offers': {
      id: '/master-dashboard/offers'
      path: '/offers'
      fullPath: '/master-dashboard/offers'
      preLoaderRoute: typeof MasterDashboardOffersRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/payment-gateway': {
      id: '/master-dashboard/payment-gateway'
      path: '/payment-gateway'
      fullPath: '/master-dashboard/payment-gateway'
      preLoaderRoute: typeof MasterDashboardPaymentGatewayRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/reports': {
      id: '/master-dashboard/reports'
      path: '/reports'
      fullPath: '/master-dashboard/reports'
      preLoaderRoute: typeof MasterDashboardReportsRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/services': {
      id: '/master-dashboard/services'
      path: '/services'
      fullPath: '/master-dashboard/services'
      preLoaderRoute: typeof MasterDashboardServicesRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/settings': {
      id: '/master-dashboard/settings'
      path: '/settings'
      fullPath: '/master-dashboard/settings'
      preLoaderRoute: typeof MasterDashboardSettingsRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/subscriptions': {
      id: '/master-dashboard/subscriptions'
      path: '/subscriptions'
      fullPath: '/master-dashboard/subscriptions'
      preLoaderRoute: typeof MasterDashboardSubscriptionsRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/master-dashboard/support': {
      id: '/master-dashboard/support'
      path: '/support'
      fullPath: '/master-dashboard/support'
      preLoaderRoute: typeof MasterDashboardSupportRouteImport
      parentRoute: typeof MasterDashboardRoute
    }
    '/salons/': {
      id: '/salons/'
      path: '/salons'
      fullPath: '/salons/'
      preLoaderRoute: typeof SalonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons/$slug': {
      id: '/salons/$slug'
      path: '/salons/$slug'
      fullPath: '/salons/$slug'
      preLoaderRoute: typeof SalonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MasterDashboardRouteChildren {
  MasterDashboardAdminsRoute: typeof MasterDashboardAdminsRoute
  MasterDashboardApprovalsRoute: typeof MasterDashboardApprovalsRoute
  MasterDashboardBookingsRoute: typeof MasterDashboardBookingsRoute
  MasterDashboardCustomersRoute: typeof MasterDashboardCustomersRoute
  MasterDashboardHairstylesRoute: typeof MasterDashboardHairstylesRoute
  MasterDashboardLocationsRoute: typeof MasterDashboardLocationsRoute
  MasterDashboardMessagesRoute: typeof MasterDashboardMessagesRoute
  MasterDashboardNotificationsRoute: typeof MasterDashboardNotificationsRoute
  MasterDashboardOffersRoute: typeof MasterDashboardOffersRoute
  MasterDashboardPaymentGatewayRoute: typeof MasterDashboardPaymentGatewayRoute
  MasterDashboardReportsRoute: typeof MasterDashboardReportsRoute
  MasterDashboardServicesRoute: typeof MasterDashboardServicesRoute
  MasterDashboardSettingsRoute: typeof MasterDashboardSettingsRoute
  MasterDashboardSubscriptionsRoute: typeof MasterDashboardSubscriptionsRoute
  MasterDashboardSupportRoute: typeof MasterDashboardSupportRoute
  MasterDashboardIndexRoute: typeof MasterDashboardIndexRoute
}

const MasterDashboardRouteChildren: MasterDashboardRouteChildren = {
  MasterDashboardAdminsRoute: MasterDashboardAdminsRoute,
  MasterDashboardApprovalsRoute: MasterDashboardApprovalsRoute,
  MasterDashboardBookingsRoute: MasterDashboardBookingsRoute,
  MasterDashboardCustomersRoute: MasterDashboardCustomersRoute,
  MasterDashboardHairstylesRoute: MasterDashboardHairstylesRoute,
  MasterDashboardLocationsRoute: MasterDashboardLocationsRoute,
  MasterDashboardMessagesRoute: MasterDashboardMessagesRoute,
  MasterDashboardNotificationsRoute: MasterDashboardNotificationsRoute,
  MasterDashboardOffersRoute: MasterDashboardOffersRoute,
  MasterDashboardPaymentGatewayRoute: MasterDashboardPaymentGatewayRoute,
  MasterDashboardReportsRoute: MasterDashboardReportsRoute,
  MasterDashboardServicesRoute: MasterDashboardServicesRoute,
  MasterDashboardSettingsRoute: MasterDashboardSettingsRoute,
  MasterDashboardSubscriptionsRoute: MasterDashboardSubscriptionsRoute,
  MasterDashboardSupportRoute: MasterDashboardSupportRoute,
  MasterDashboardIndexRoute: MasterDashboardIndexRoute,
}

const MasterDashboardRouteWithChildren = MasterDashboardRoute._addFileChildren(
  MasterDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BookDemoRoute: BookDemoRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MasterDashboardRoute: MasterDashboardRouteWithChildren,
  OffersRoute: OffersRoute,
  RegisterSalonRoute: RegisterSalonRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  WeddingPackagesRoute: WeddingPackagesRoute,
  HairstylesSlugRoute: HairstylesSlugRoute,
  SalonsSlugRoute: SalonsSlugRoute,
  HairstylesIndexRoute: HairstylesIndexRoute,
  SalonsIndexRoute: SalonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
